const palette = {
  black: "#000000",
  nearBlack: "#0A0A0A",
  surface: "#141414",
  card: "#1C1C1E",
  cardAlt: "#232323",
  violet: "#7C3AED",
  violetLight: "#A855F7",
  violetDim: "#5B21B6",
  violetGlow: "rgba(124, 58, 237, 0.25)",
  violetGlowStrong: "rgba(124, 58, 237, 0.45)",
  white: "#FFFFFF",
  textSecondary: "#9CA3AF",
  textMuted: "#6B7280",
  border: "#2A2A2A",
  borderLight: "#333333",
  error: "#EF4444",
  success: "#22C55E",
  overlay: "rgba(0,0,0,0.6)",
};

export default {
  dark: {
    background: palette.nearBlack,
    surface: palette.surface,
    card: palette.card,
    cardAlt: palette.cardAlt,
    text: palette.white,
    textSecondary: palette.textSecondary,
    textMuted: palette.textMuted,
    tint: palette.violet,
    tintLight: palette.violetLight,
    tintDim: palette.violetDim,
    tintGlow: palette.violetGlow,
    tintGlowStrong: palette.violetGlowStrong,
    tabIconDefault: palette.textMuted,
    tabIconSelected: palette.violet,
    border: palette.border,
    borderLight: palette.borderLight,
    error: palette.error,
    success: palette.success,
    overlay: palette.overlay,
  },
};
